---
- name: Install Apache Server
  hosts: all
  become: yes
 
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
 
    - name: Install Apache
      apt:
        name: apache2
        state: present
 
    - name: Ensure Apache is started and enabled at boot
      service:
        name: apache2
        state: started
        enabled: yes
