---
- name : sample ansible playbook
  hosts : all
  become : yes
  tasks :
    - name: Update apt package manager 
      apt: 
        update_cache: yes
        
    - name : install nginx
      apt :
        name : nginx
        state : present

    - name: start nginx
      service:
          name: nginx
          state: started
