name: Run ansible

on:
  push:
    branches:
      main
  
jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: run ansible
        run: ansible-playbook -i inventory playbook.yml
        env: 
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          
          
