name: Run ansible

on:
  push:
    branches:
      main
      #triggerr

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install SSH Client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: setup ssh key for ansible
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > github.pem
          chmod 400 github.pem
          ssh -o StrictHostKeyChecking=no -i github.pem ubuntu@${{ secrets.EC2_PUBLIC_DNS }}
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 52.91.222.15 >> ~/.ssh/known_hosts
          cp index.html .

      - name: run ansible
        run: |
          ansible-playbook -i inventory.ini playbook.yml
        
          
          
