name: build and test code

on:
  push:
    paths:
      main/TestFile.txt

  pull_request:
    branches:
      main

jobs:
  autobuild:
   runs-on: ubuntu-latest
   steps:
   - name: checkout to main
     uses: actions/checkout@v2

   - name: run the command
     run: echo "This build was triggered automatically"
