name: Deploy application to S3

on:
  push:
    branches:
      main

  pull_request:
    branches:
      main

jobs:
  build_app:
   runs-on: ubuntu-latest

   steps:
     - name: checkout
       uses: actions/checkout@v2

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: docker build
       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/new-image:${{ github.sha }} .

     - name: docker push
       run: docker push ${{ secrets.DOCKER_USERNAME }}/new-image:${{ github.sha }}

  deploy_to_s3:
    runs-on: ubuntu-latest
    needs: build_app
    steps:
     - name: checkout
       uses: actions/checkout@v2

     - name: Install SSH Client
       run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
 
     - name: Add SSH Key
       run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > github.pem
          chmod 400 github.pem
 
      # Run commands on EC2 instance
     - name: Run Command on EC2
       run: |
          ssh -o StrictHostKeyChecking=no -i github.pem ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
          echo "Running commands on EC2 instance"
          sudo docker pull new-image:latest
          sudo docker run -d -p 80:80 new-image:latest
          EOF

     - name: setup aws cli
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}

     - name: sync s3
       run: aws s3 sync ./ s3://$S3_BUCKET_NAME

       env:
         S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      
       
  


