name: Deploy application to S3

on:
  push:
    branches:
      - main

jobs:
  deploy-to-s3:
   runs-on: ubuntu-latest

   steps:
     - name: checkout
       uses: actions/checkout@v2

     - name: setup aws cli
       uses: actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}

     - name: sync s3
       run: aws s3 sync ./ s3://$S3_BUCKET_NAME --delete --acl public-read

       env:
         S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
       
  


