name: Docker build and push workflow

on:
  push:
    paths:
      - Dockerfile
  pull_request:
    branches:
      main
  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout to main branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/new-image:${{ github.sha }} .

      - name: docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/new-image:${{ github.sha }}
  
