name: Trigger child repo

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  trigger-repo:
    runs-on: ubuntu-latest
    steps:
      - name: trigger another repo
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: sharook-98/TestRepo
          token: ${{ secrets.TOKEN }}
          event_type: my-event
