name: Trigger child repo

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  trigger-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
   #triggers another workflow     
      - name: trigger another repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: sharook-98/TestRepo  # Replace with the target repo's details
          event-type: trigger-workflow
