name: Trigger child repo

on:
  push:
    paths:
      - .github/workflow/HeadRepo.yaml
  pull_request:
    branches:
      main

jobs:
  trigger-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
   #triggers another workflow     
      - name: trigger another repo
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: sharook-98/TestRepo
          token: ${{ secrets.TOKEN }}
          event-type: trigger
