name: Trigger child repo

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  trigger-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
   #triggers another workflow     
      - name: trigger another repo
        run: |
          #setting up the required variable
          repo_owner="sharook-1998"
          repo_name="TestRepo"
          event_type="trigger-workflow"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\",\"unit\": false, \"integration\": true}}"
