name: Create Cluster

on: 
  push:
    branches:
      main
      #trigger

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/k8s:latest
         
      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1

      - name: run Kubectl commands
        run: |
          kubectl run test-image-nginx --image=sharook1998/k8s
