name: Depoly container in k8s cluster

on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2

      - name : setup docker
        uses : docker/setup-buildx-action@v2

      - name : login docker
        uses : docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name : build and push image
        uses : docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/k8s:latest

  deploy-to-k8s:
    needs : build
    runs-on : ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2

      - name : configure aws cli
        uses : aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}

      - name : install SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name : add ssh key and ssh to EC2 machine
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > test.pem
          chmod 400 test.pem
          ssh -o StrictHostKeyChecking=no -i test.pem ubuntu@ec2-44-220-154-45.compute-1.amazonaws.com

      - name : setup docker
        uses: docker/setup-buildx-action@v2

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1

      - name: Run Kubectl commands
        run: |
          kubectl run test-image-nginx --image=sharook1998/k8s

          

          
