name: Depoly container in k8s cluster

on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2

      - name : setup docker
        uses : docker/setup-buildx-action@v2

      - name : login docker
        uses : docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name : build and push image
        uses : docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/k8s:latest

  deploy-to-k8s:
    needs : build
    runs-on : ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2

      - name : configure aws cli
        uses : aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}

      - name : install SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name : add ssh key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > test.pem
          chmod 400 test.pem

      - name : run k8s commands for installation
        run : |
          ssh -o StrictHostKeyChecking=no -i test.pem ubuntu@ec2-44-220-154-45.compute-1.amazonaws.com << 'EOF'
          echo "Running Docker installation commands on EC2 instance"
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce
          sudo systemctl status docker
          

          
