name: List the files in the Repository

on:
 push:
   branches:
    main
     paths:
      main/List_file.yml
      
jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
    - name: checkoutaction
      uses: actions/checkout@v2

    - name: list files cmd
      run: |
        echo "List of files available in the repository (Main Branch)"
        ls -ltr

