name: List the files in the Repository

on:
 push:
   paths:
      - .github/workflows/List_file.yml
      #trigger
      
jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
    - name: checkoutaction
      uses: actions/checkout@v2

    - name: list files cmd
      run: |
        echo "List of files available in the githib repository (Main Branch)"
        ls -ltr

