name: Trigger the job manually

on:
  workflow_dispatch:
  
jobs:
  manual_job:
    runs-on: ubuntu-latest

    steps:
      -  name: checkout event
         uses: actions/checkout@v2

      -  name: Message to display
         run: echo "This job was triggered manually"
      
