name: trigger when new files are added to folder

on:
  push:
    paths:
      - Project 1/**

jobs:
  NewFileTrigger:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: new files added
        run: |
          echo "Listing files in folder"
          ls -R Project 1

      - name: add new files
        run: echo " add new files in project 1 folder "
  
