name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "sharook-98"
        git config --global user.email "sharookk98@gmail.com"

    - name: Get version from file
      run: |
        VERSION=$(cat version.txt)
        echo "::set-output name=VERSION::$VERSION"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: app
        release_name: app 1.0
        draft: false
        prerelease: false
        

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: https://github.com/sharook-98/GitHub-actions-usecases/
        asset_path: ./path/to/your/asset.zip
        asset_name: sharook-98-asset.zip
        asset_content_type: application/zip
